leftnav:
- identifier: 61270b4a-5abc-5fdf-b06e-32fead97b9e1
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: e5a7fe31-614c-92c6-64a4-27a6ae1a65eb
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 753197e5-0b16-ee7d-0340-a605c98e0718
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: a1b5ab94-b32e-92a2-777b-3ce81b841896
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 40
- identifier: 3088c76f-c62e-aad1-a563-0f7394211483
  name: Assignments
  url: /pages/assignments
  weight: 50
